name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Load Twitch secrets
        uses: ozaytsev86/create-env-file@v1
        with:
          file-name: 'twitch.properties'
          ENV_client_id: ${{ secrets.CLIENT_ID }}
          ENV_client_secret: ${{ secrets.CLIENT_SECRET }}
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload a build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'releaseApk'
          path: './app/build/outputs/apk/release/*.apk'
